# save this as environment.yml and run: conda env create -f environment.yml
name: ragapp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - streamlit
      - requests
      - beautifulsoup4
      - trafilatura
      - PyPDF2
      - pdf2image
      - pillow
      - easyocr
      - langchain
      - langchain-community
      - langchain-huggingface
      - langchain-openai
      - faiss-cpu
      - rank-bm25
      - sentence-transformers
      - transformers
      - huggingface-hub
      - pandas
      - numpy
      - pyparsing
