QDRANT_URL="https://b7ddd683-3853-4ca5-bd46-0f373c16830a.eu-west-2-0.aws.cloud.qdrant.io"
QDRANT_API_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIn0.VdYYAYE3cVBHZdFfM29AFJRtCoGPoo0ROnPf8pIXaBE"
